# Generated by Django 3.2 on 2024-03-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_auto_20240306_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='job_description',
            new_name='project_description',
        ),
        migrations.AddField(
            model_name='member',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_team', to='MM.member'),
        ),
    ]
