# Generated by Django 3.2 on 2024-03-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0005_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermotivator',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MotivatorChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(auto_now_add=True)),
                ('member_motivator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='MM.membermotivator')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
    ]
