# Generated by Django 3.2 on 2024-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0006_auto_20240327_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivatorchangelog',
            name='new_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motivatorchangelog',
            name='previous_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
